spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr
    username: postgres
    password: techbankRootPsw
#Hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        formal_sql: true
jwt:
  secret: ${SECRET_KEY}