spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr
    username: ${DB_USR}
    password: ${DB_PWD}
#Hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        formal_sql: true
jwt:
  secret: ${SECRET_KEY}